### ISSUE TITLE
An answer to the twitter question :)

### ISSUE THREAD

**Issue by matklad** [glaebhoerl/rust-notes#1]
You've [asked](https://twitter.com/glaebhoerl/status/686983280957255681)

> There was a post or talk discussing how people always want new-and-unfamiliar things to have loud and verbose syntax at first, and then short and convenient syntax after they become familiar. (E.g.: C++ templates, C# delegates.) Anyone remember it?

It was Bjarne Stroustrup, [slide 14](https://view.officeapps.live.com/op/view.aspx?src=http%3a%2f%2fvideo.ch9.ms%2fsessions%2flangnext%2f2014%2fBjarne.pptx).

Sorry for this strange way to contact you, but I don't have a twitter account :)

**Comment by glaebhoerl** [comment]
Wow, thanks a lot! Not sure I would have ever found that. (Vaguely recall having read it before, now that I see it again, but the connection was lost.)

I think you might have the distinction of being the first person to ever go back and answer one of my questions from that list. (Not even people with actual twitter accounts have done it!)

**Comment by glaebhoerl** [comment]
Gonna mark this is as resolved. You don't mind if I credit you on twitter, right? :)

**Comment by matklad** [comment]
> You don't mind if I credit you on twitter, right? :)

Yep, thanks! :)

**Comment by matklad** [comment]
Hey, https://mobile.twitter.com/glaebhoerl/status/919320117330235392 is a too interesting question to bypass! :) 

>at some level, I'm wondering "can frontends for different languages never benefit from any sharing"

An interesting example of profound compiler's frontend sharing is IntelliJ platform. IntelliJ IDE`s are not technically compilers, because they don't actually generate code, but their front-ends are a match for compilers, and can even even be superior on some axis (incrementality&laziness, error recovery, and a ton of IDE-specific features like autoformatting). So, IntelliJ has mature frontends for at least Java/Scala/Kotlin/Groovy, Python, JavaScript, Go, Rust, PHP, Ruby, C++ and probably a ton of other languages which I've forgotten. 

The sharing of course includes "library level" sharing, like a common parser library/parser generator. However, the actual data structure which is used to represent syntactic tree (`psi`), is also shared. Of course, each language defines its own inheritors of `PsiElement`, but there are a lot of code which does not care about particular sub-classes for `PsiElement`s. Some concrete examples are
 
* When pressing `Ctrl+B`on an element, which is a reference, the "go to definition" action is invoked, when pressing `Ctrl+B` on an element, which is a declaration (is `PsiNamedElement`), "find usages" action is invoked. 

* Go to definition works across languages: `Ctrl+B` in an `html` template file can bring you to python class.

* It's possible to embed one language inside another, like we do to embed test code in Rust inside Kotlin:
![image](https://user-images.githubusercontent.com/1711539/31648784-4c0fab8a-b318-11e7-97c7-66f10edbdac9.png)

* The whole indexing infrastructure (for example, and index which maps class fully-qualified name to the PsiElement of a class in a file) is shared across different languages, and you can store different languages in the same index (Like, for example, an index of all comments).


And the most impressive example for me was the [FlipCommaIntention](https://github.com/JetBrains/intellij-community/blob/e4efb836cd8cb0d6f648237aa77fc59ac4315921/platform/lang-impl/src/com/intellij/openapi/editor/actions/FlipCommaIntention.java). Intentions are actions which are available and suggested automatically depending on context. The "Flip ','" suggest to flip elements of the comma separated list, like, for example `fn foo(foo: HashMap<i32, i32>, bar: String) -> fn foo(bar: String, foo: HashMap<i32, i32>)` if the caret is on the ,``. This intention needs access to syntax tree, because elements to be flipped can contain commas themselves, like in the example above. And I was really amazed when I realized that this intention works for the Rust language, even though I have not implemented anything specifically to support it! It works, because it does not care about the langauge, all it needs to see is a three sibling elmenets, L, C, R, where the types of L and R are the same, and the text of C is ','.

For JVM based languages specifically, there's even a more profound sharing via [`Unified Ast`](https://github.com/JetBrains/intellij-community/blob/e4efb836cd8cb0d6f648237aa77fc59ac4315921/uast/uast-common/src/org/jetbrains/uast/baseElements/UElement.kt) which allows to write, say, Spring support once for Java/Groovy/Kotlin.

**Comment by glaebhoerl** [comment]
Very interesting, thank you! Hmm... is there any sharing at the level of things like typechecking?

(also, are you secretly following me on twitter or just lurking somehow :D)

**Comment by matklad** [comment]
> is there any sharing at the level of things like typechecking?

No, there are only common patterns (lazyness, file-based indexes, coarse and fine-grained caches) and libraries, and every language has it's own type checker

>(also, are you secretly following me on twitter or just lurking somehow :D)

I still don't have a twitter account, but I read a couple of twitterers from time to time :)

**Comment by glaebhoerl** [comment]
Ah, that's how it started for me, too :)
